#!/usr/bin/env python3
# Copyright 2021 NetworkRADIUS SARL (legal@networkradius.com)
# Author: Jorge Pereira <jpereira@freeradius.org>
# -*- coding: utf-8 -*-
#
###

__author__ = "Jorge Pereira <jpereira@networkradius.com>"
__version__ = "0.1a"

import argparse
import base64
import dns.resolver
import os, errno
import OpenSSL.crypto
import re
import sys
import shutil
import traceback
import wget

from urllib.parse import urlparse

DEFAULT_CERT_DEST = "/etc/ssl/automatic-eap"

dns_server = None

def show_cert(_cert_file):
	try:
		cert = OpenSSL.crypto.load_certificate(OpenSSL.crypto.FILETYPE_PEM, open(_cert_file).read())
		print("\t> Issued to = \"{0}\"".format(cert.get_subject().CN))
		print("\t> Issued By = \"{0}\"".format(cert.get_issuer().CN))
	except Exception as e:
		raise ValueError("Can't load certificate file: {0}".format(_cert_file))

def overwrite_url(_url, _host):
	parsed = urlparse(_url)
	parsed = parsed._replace(netloc = _host).geturl()
	return parsed

def downlod_file(_url, _dest):
	try:
		_destfile = "{0}/{1}".format(_dest, os.path.basename(_url))
		if os.path.isfile(_destfile):
			os.remove(_destfile)

		_destdir = os.path.dirname(_destfile)
		if not os.path.isdir(_destdir):
			os.mkdir(_destdir)

		print("\t[-] Save \"{0}\" in \"{1}\"".format(_url, _destfile))
		wget.download(_url, out = _destfile)
		print()

		return _destfile
	except Exception as e:
		raise ValueError("Can't download {0} in {1}".format(_url, _dest))

def dns_get_cert_url(_type, _domain):
	try:
		res = dns.resolver.Resolver(configure=False)
		cert_domain = "{0}.{1}".format(_type, _domain)

		print("\t[-] Lookup the domain: \"{0}\"".format(cert_domain))

		if dns_server:
			res.nameservers = [dns_server]

		for row in res.resolve(cert_domain, "CERT"):
			# As described in https://datatracker.ietf.org/doc/html/rfc4398#section-2.2
			(_begin, _type, _tag, _algo, _cert, _end) = re.split(r"^(\d) (\d) (\d) (.+)$", str(row))
			return base64.b64decode(_cert).decode('ascii')
	except Exception as e:
		raise ValueError("Can't resolve {0}".format(cert_domain))

def create_eapol_conf(_wpa_conf, _ca_cert, _server_cert, _radius_user, _radius_pass):
	conf =  """
#
# Generated by Automatic-EAP
#
network={{
\tkey_mgmt=WPA-EAP
\teap=TTLS
\tidentity=\"{0}\"
\tanonymous_identity="anonymous@example.org"
\tca_cert=\"{2}\"
\tpassword=\"{1}\"
\tphase2=\"auth=PAP\"
}}\n"""

	with open(_wpa_conf, 'w') as f:
		f.write(conf.format(_radius_user, _radius_pass, _ca_cert))

def _main():
	global dns_server

	parser = argparse.ArgumentParser(description = "Bootstrap Automatic-EAP informations automatically")
	parser.add_argument("-d", "--domain", dest = "domain", help = "Domain to bootstrap the Automatic-EAP", required = True)
	parser.add_argument("-s", "--dns-server", dest = "dns_server", help = "DNS server address to use.", required = False)
	parser.add_argument("-c", "--cert-dest", dest = "cert_dest", help = "Certificate destination directory.", required = False, default = DEFAULT_CERT_DEST)
	parser.add_argument("-H", "--overwrite-dns-cert-host", dest = "url_host", help = "Overwrite the HOST from DNS/CERT reply.", required = False)
	parser.add_argument("-w", "--eapol-test-conf", dest = "eapol_conf", help = "Destination of generated eapol_test.conf file.", default = "/tmp/eapol_test.conf", required = False)
	parser.add_argument("-S", "--radius-server", dest = "radius_server", help = "RADIUS Server", default = "localhost", required = True)
	parser.add_argument("-e", "--radius-secret", dest = "radius_secret", help = "RADIUS Secret", default = "testing123", required = False)
	parser.add_argument("-u", "--radius-user", dest = "radius_user", help = "RADIUS User", required = True)
	parser.add_argument("-p", "--radius-pass", dest = "radius_pass", help = "RADIUS Pass", required = True)
	args = parser.parse_args()

	try:
		print("[+] Automatic-EAP bootstrap for \"{0}\"".format(args.domain))

		if args.dns_server:
			print("\t[-] Set specific DNS server: \"{0}\"".format(args.dns_server))
			dns_server = args.dns_server

		#
		# Lookup the _ca._cert ...
		#
		ca_cert_url = dns_get_cert_url("_ca._cert._eap", args.domain)
		print("\t > ca_cert = \"{0}\"".format(ca_cert_url))
		if args.url_host:
			ca_cert_url = overwrite_url(ca_cert_url, args.url_host)
		ca_cert_file = downlod_file(ca_cert_url, args.cert_dest)
		show_cert(ca_cert_file)

		#
		# Lookup the _server._cert ...
		#
		server_ca_url = dns_get_cert_url("_server._cert._eap", args.domain)
		print("\t > server_ca = \"{0}\"".format(server_ca_url))
		if args.url_host:
			server_ca_url = overwrite_url(server_ca_url, args.url_host)
		server_ca_file = downlod_file(server_ca_url, args.cert_dest)
		show_cert(server_ca_file)

		#
		# Generate wpa_supplicant.conf
		#
		print("\t[-] Generate the \"{0}\"".format(args.eapol_conf))
		create_eapol_conf(args.eapol_conf, ca_cert_file, server_ca_file, args.radius_user, args.radius_pass)

		#
		# Validate the connection
		#
		print("# Command to validate:")
		print("eapol_test -c {0} -a {1} -s {2}".format(args.eapol_conf, args.radius_server, args.radius_secret))

	except Exception as e:
		print("** ERROR: {0}".format(str(e)))
		sys.exit(-1)

if __name__ == "__main__":
	_main()
